### ISSUE TITLE
Add support for compiling with Visual Studio 2019

### ISSUE THREAD

**Issue by NN---** [lewissbaker/cppcoro#119]
AppVeyor has VS 2019

**Comment by lewissbaker** [comment]
See https://github.com/lewissbaker/cppcoro/pull/125 for changes needed to support vs2019 on appveyor.

I have not yet merged it because vs2019 was failing some optimised tests.
I haven't had a chance to investigate the cause of these crashes (not sure if it's exposing a bug in cppcoro or a bug in msvc).

**Comment by NN---** [comment]
There are known bugs with coroutines in MSVC with optimizations enabled.
Unfortunately I couldn't reproduce them in a way that I can give a sample project to MS.
If you have a consistent reproduction, you should ask MS to check it, and then they will fix.

**Comment by NN---** [comment]
See this: https://developercommunity.visualstudio.com/content/problem/498874/co-await-optimization-bugs-in-visual-studio-2019-r.html?childToView=716966#comment-716966
You should try again when 16.4 will be released to AppVeyor.

**Comment by joemmett** [comment]
Hi - I'm a developer on the MSVC team and am working on finishing the coroutine support in VS 2019. We've recently harnessed cppcoro as part of our internal testing of the toolchain and are internally tracking bugs related to the optimized test failures, but are running all the others regularly. I also have a small number of patches to submit to address some issues due to STL header reorganization that I hope to get into a PR soon.

**Comment by lewissbaker** [comment]
@joemmett I've updated the PR to rebuild with the latest Visual Studio 2019 on AppVeyor (MSVC 14.24.28314).

Compilation seems to be failing with odd front-end error messages:
https://ci.appveyor.com/project/lewissbaker/cppcoro/builds/30413745/job/1wf0ccttb8tegami#L35

Is MSVC getting getting confused by the use of captures within an immediately invoked coroutine lambda?

**Comment by NN---** [comment]
You can try [/experimental:newLambdaProcessor](https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019)

**Comment by joemmett** [comment]
@lewissbaker Sort of - that was a bug with resolving certain names within a lambda, it doesn't necessarily need to be immediately invoked. It's specific to using /std:c++latest, but can be worked around by either using the switch suggested by @NN--- or, even better, `/permissive-`. I do recommend using /permissive- when you can.

I tried reproducing this merge locally and adding /permissive-. I get a good build and all tests pass except two that I also saw last week: 

1. A runtime crash in one of the async_auto_reset_event_tests in optimized x64 builds. This looks to be intermittent and I'm not sure if it's a codegen bug or some timing/race issue, but I've opened a bug against the back-end group for investigation.
2. x86 optimized builds are failing the 'cancel read' test because the operation_cancelled exception is not being caught by the catch handler. I've filed this with the back-end group.

**Comment by lewissbaker** [comment]
Thanks @joemmett. I've updated the build config to add `/permissive-` and the CI builds seem to be getting farther now.

I'm still seeing the x86 optimised tests crash (I assume this is the issue you describe).

It's possible that the async_auto_reset_event_tests could be crashing because of a race condition in the static_thread_pool implementation that I've occasionally seen (e.g. see #114). Or it could be unrelated...

**Comment by tnovotny** [comment]
Any progress on this?

**Comment by NN---** [comment]
VS 2019 16.5 fixed issues with generators and lambda.
We have encountered them in our project too, but now we don’t see any issue.
Please try the latest version.

**Comment by NN---** [comment]
VS 2019 16.5 fixed issues with generators and lambda.
We have encountered them in our project too, but now we don’t see any issue.
Please try the latest version. #

**Comment by tnovotny** [comment]
I tried building this branch with 16.5.4 and it did not build. I also tried building master, but cake did not do anything there. mainly these two errors.

```
D:\work\externals\cppcoro\lib\cancellation_state.cpp(82): error C2220: the following warning is treated as an error
D:\work\externals\cppcoro\lib\cancellation_state.cpp(82): warning C4996: 'std::atomic_init': warning STL4028: std::atomic_init() overloads are deprecated in C++20. The constructors of std::atomic provide equivalent functionality. You can define _SILENCE_CXX20_ATOMIC_INIT_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
```
D:\work\externals\cppcoro\test\doctest\doctest.h(3552): error C2039: 'uncaught_exception': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.26.28801\include\map(25): note: see declaration of 'std'
```

**Comment by NN---** [comment]
> D:\work\externals\cppcoro\lib\cancellation_state.cpp(82): warning C4996: 'std::atomic_init': warning STL4028: std::atomic_init() overloads are deprecated in C++20. The constructors of std::atomic provide equivalent functionality. You can define _SILENCE_CXX20_ATOMIC_INIT_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
> ```
This one is fixed in master https://github.com/lewissbaker/cppcoro/pull/140
Try merging from master and then build again.

> ```
> D:\work\externals\cppcoro\test\doctest\doctest.h(3552): error C2039: 'uncaught_exception': is not a member of 'std'
>```
This is deprecated in C++17 and removed in C++29
https://en.cppreference.com/w/cpp/error/uncaught_exception

There is `int uncaught_exceptions() noexcept;` instead.

**Comment by tnovotny** [comment]
Ok, after merging in master it looks _much_ better. I still get the 
```
error C2039: 'uncaught_exception': is not a member of 'std'
``` 
which i can fix, and i also get
```
...\cppcoro\test\multi_producer_sequencer_tests.cpp(118) : warning C6262: Function uses '131780' bytes of stack:  exceeds /analyze:stacksize '16384'.  Consider moving some data to heap.
...\cppcoro\test\multi_producer_sequencer_tests.cpp(162) : warning C6262: Function uses '131772' bytes of stack:  exceeds /analyze:stacksize '16384'.  Consider moving some data to heap.
```

**Comment by tnovotny** [comment]
After patching doctest, I at least have some libs i can link against, but one of the tests fails
```
...\cppcoro\test\cancellation_token_tests.cpp(261):
TEST SUITE: cancellation_token tests
TEST CASE:  cancellation registration single-threaded performance

...\cppcoro\test\cancellation_token_tests.cpp(334): MESSAGE: Individual took 3625us (36.25 ns/item)

..\cppcoro\test\cancellation_token_tests.cpp(334): MESSAGE: Batch10 took 45694us (45.694 ns/item)

...\cppcoro\test\cancellation_token_tests.cpp(334): MESSAGE: Batch50 took 247985us (49.597 ns/item)

 starting write
 starting read
test build/windows_x86_msvc15_optimised/test/run.exe failed with exit code -1073740791 (0x-3ffffbf7)
Linking build\windows_x64_msvc15_debug\test\run.exe
Testing build/windows_x64_msvc15_debug/test/run.exe
Linking build\windows_x64_msvc15_optimised\test\run.exe
Generating code
Finished generating code
Testing build/windows_x64_msvc15_optimised/test/run.exe
```

**Comment by NN---** [comment]
Can you try with 16.6 preview ? It might be a MSVC coroutine bug.

**Comment by joemmett** [comment]
@tnovotny @NN--- There is a known bug we are tracking internally related to exceptions not being caught on x86 only. I can't say for sure this is the same test that is failing from the log above, though.

**Comment by NN---** [comment]
@joemmett Can you share more information how it is reproduced ?
We are using corourines heavily and would like to know if there are issues.
Thanks.

**Comment by joemmett** [comment]
@NN--- If it's the same bug, it's an issue with the exception in the "cancel read" test in file_tests.cpp not being caught. It's specific to X86 and only in optimized builds. The catch handler for operation_cancelled is not catching the exception thrown from the coroutine and it escapes out from the test function.

**Comment by tnovotny** [comment]
recompiling with 16.6 doesn't change anything.
```
cake
MSVC (x64): C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.26.28801
...
===============================================================================
D:\work\externals\cppcoro\test\cancellation_token_tests.cpp(261):
TEST SUITE: cancellation_token tests
TEST CASE:  cancellation registration single-threaded performance
...
 starting write
 starting read
test build/windows_x86_msvc15_optimised/test/run.exe failed with exit code -1073740791 (0x-3ffffbf7)
...
```

**Comment by tnovotny** [comment]
@joemmett 
> Can you share more information how it is reproduced ?

well, not much more than what I've already shared. I clonend the repo, switched to the vs2019 branch, merged master into the branch, built with cake, and the test that fails is executed as part of the build.
